version: '3'

services:
  docs:
    image: cookiecutter_django_ninja_example_local_docs
    container_name: cookiecutter_django_ninja_example_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cookiecutter_django_ninja_example:/app/cookiecutter_django_ninja_example:z
    ports:
      - '9000:9000'
    command: /start-docs
